### ISSUE TITLE
Error on tear-down when all tests succeeded

### ISSUE THREAD

**Issue by evnu** [evnu/docception#2]
It appears that calling `Application.stop(:ex_unit)` on shutdown fails if no test failed during the docception run:

```
21:30:38.920 [info]  Application ex_unit exited: :stopped
** (exit) exited in: GenServer.call(ExUnit.Server, :modules_loaded, 5000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir) lib/gen_server.ex:999: GenServer.call/3
    (ex_unit) lib/ex_unit.ex:193: anonymous fn/1 in ExUnit.start/1
    (elixir) lib/kernel/cli.ex:121: anonymous fn/3 in Kernel.CLI.exec_fun/2
[1]    22379 exit 1     mix docception *.md
```

**Comment by evnu** [comment]
I can reproduce the error with revision 09ba947 and the following call to the mix task:

```
$ mix docception <(echo "")
```

As this does not happen with `mix docception README.md`, this might be related to the size of the markdown file.

**Comment by evnu** [comment]
The crash happens [here](https://github.com/elixir-lang/elixir/blob/v1.9/lib/ex_unit/lib/ex_unit.ex#L193) within ExUnit:

```elixir
System.at_exit(fn
  0 ->
    time = ExUnit.Server.modules_loaded()
    options = persist_defaults(configuration())
    %{failures: failures} = ExUnit.Runner.run(options, time)

    System.at_exit(fn _ ->
      if failures > 0, do: exit({:shutdown, 1})
    end)

  _ ->
    :ok
end)
```

**Comment by evnu** [comment]
The error is caused by docception when shutting down [ExUnit manually](https://github.com/evnu/docception/blob/master/lib/mix/tasks/docception.ex#L30). This shutdown was needed to ensure that all failures are written to the console on shutdown. See [this](https://github.com/evnu/docception/blame/master/README.md#L62) TODO in the README:

> Determine how to ensure that errors are written before the task ends; avoid stopping ex_unit in mix task.

**Comment by evnu** [comment]
So, shutting down ExUnit when the exit code is 0 is bad. Shutting it down when the exit code is not zero should not hurt (unless the exit handler mentioned above changes). As we only need to ensure that all output is written if there is an actual error, we can introduce our own exit handler, which shuts down ExUnit if an error was detected.
